### PR TITLE
#19 Fix missing header files in install folder

### LINKED ISSUE #19: Missing header files in install folder
To be able to use the API for multiple jobs some header files seem to be missing in install folder. At least the following files are required:

- `Scenario.h`, `Scenarios.h` from `Common`, to define the contents of the multiple jobs.
- `MultipleJobs.h`, `MultipleJobsFactory.h` and `MultipleJobsXmlHandler.h` from `API/multipleJobs` to build and serialize the multiple jobs definition.

### PR DESCRIPTION
**Pull request by zamarrenolm**
closes #19

### CODE REVIEW

**Review by gautierbureau — APPROVED** [review]

**Comment by rosiereflo** [comment]
This PR also integrates the commit for issue #16, could you please remove it?

**Comment by zamarrenolm** [comment]
> This PR also integrates the commit for issue #16, could you please remove it?

Sure, sorry for that.

What do you prefer, an additional commit that reverts the changes (this PR will have 3 commits) ? Alternatively, I can close this PR and create a new one with a clean branch.

**Review by lecourtoisflo — APPROVED** [review]

**Comment by rosiereflo** [comment]
> > This PR also integrates the commit for issue #16, could you please remove it?
> 
> Sure, sorry for that.
> 
> What do you prefer, an additional commit that reverts the changes (this PR will have 3 commits) ? Alternatively, I can close this PR and create a new one with a clean branch.

I would prefer a clean PR with only one commit. The #16 commit was merged, so maybe a rebase would fix this?

**Comment by zamarrenolm** [comment]
closed. it will re-created with clean commit history

**Pull request closed without merging**
