### PR TITLE
#18 Rename exec script

### LINKED ISSUE #18: Installed exec script assumes Dynawo is installed in same dir of Dynawo algorithms
After build and install, the script to launch dynawo algorithms assumes that Dynawo installation dir is the same of the Dynawo Algorithms install dir.

In file: `execDynawoAlgorithms.sh`, the function `setEnv` sets:

```bash
DYNAWO_INSTALL_DIR=$DYNAWO_ALGORITHMS_INSTALL_DIR
```

But Dynawo could be installed in a different place ...

### PR DESCRIPTION
**Pull request by zamarrenolm**
closes #18

### CODE REVIEW

**Review by gautierbureau — APPROVED** [review]

**Comment by rosiereflo** [comment]
Changing the name of this file would require to modify private projects that rely on it. I would prefer to keep its name to avoid breaking something silently

**Comment by zamarrenolm** [comment]
> Changing the name of this file would require to modify private projects that rely on it. I would prefer to keep its name to avoid breaking something silently

So we just leave the comment inside the script and keep the original name ?

**Comment by rosiereflo** [comment]
> > Changing the name of this file would require to modify private projects that rely on it. I would prefer to keep its name to avoid breaking something silently
> 
> So we just leave the comment inside the script and keep the original name ?

Yes if possible

**Comment by zamarrenolm** [comment]
> > > Changing the name of this file would require to modify private projects that rely on it. I would prefer to keep its name to avoid breaking something silently
> > 
> > 
> > So we just leave the comment inside the script and keep the original name ?
> 
> Yes if possible

No problem about that for PowSyBl DynaFlow integration in Security Analysis. We are not relying on this script for running the simulations, we use directly the API.

**Comment by rosiereflo** [comment]
OK, but one of the private projects is using this script to launch Dynawo simulations

**Pull request closed without merging**
